INSERT INTO FORNECEDOR (CNPJ_FOR, NOME_FOR, FANTASIA_FOR, END_FOR, BAIRRO_FOR, ESTADO_FOR, TEL_FOR, EMAIL_FOR, CLASSIFICACAO_FOR, CIDADE_FOR, CEP_FOR)
	VALUES ('48524219000116', 'IRMAOS BARTOLOMEU LTDA', 'IRMAOS BARTOLOMEU', 'AV DOM LUIZ AMARAL MOUSINHO, 1547','centro','SP', '36649900', 'irmaosbartolomeu@bartolomeu.com.br', 3, 'Brodowski', '14340-000');

INSERT INTO PRODUTO (DESCRICAO_PROD, QTDE_ESTOQUE_PROD) 
	VALUES ('Notebook Dell Inspirion 15r', 15);

INSERT INTO ANUNCIO (TEXTO_ANU, VALOR_ANU, IMG_ANU, DATA_INICIO_ANU, DATA_FIM_ANU, QTDE_MIN_ANU, QTDE_MAX_ANU, ATIVO_ANU, FORNECEDOR_ANU, PRODUTO_ANU)
	values ('Confira as principais especificações: Processador Intel Core i7 de 3ª Geração de 2,1 GHz (4 núcleos e 8 threads) 8 GB de memória RAM DDR3 1600 MHz', 2200.99, 'img/product-1.jpg', '2015-06-11', '2015-10-11', 5, 10, 'T', 1, 1);
    
INSERT INTO CLIENTE (CPF_CLI, NOME_CLI, SOBRENOME_CLI, END_CLI, BAIRRO_CLI, COMPL_CLI, ESTADO_FOR, TEL_CLI, CEL_CLI, CIDADE_CLI,CEP_CLI, DATA_NASC_CLI, EMAIL_CLI, SENHA)
	VALUES ('4878258245353', 'Cliente teste', 'sobrenome', 'rua das flores', 'Cohab I', 'Casa', 'SP', '35467382', '993847563', 'Sao Paulo','14001000', '2015-10-13', 'teste@teste.com', '1234');

INSERT INTO GRUPO (QTDE_ATUAL_GRU, ANUNCIO_GRU)
	VALUES (0, 1);

INSERT INTO PARTICIPA (CLIENTE_PAR, GRUPO_PAR, ATIVO_PAR)
	VALUES ();

INSERT INTO PEDIDO (QUANTIDADE_PED, ANUNCIO_PED, GRUPO_PED)
	VALUES ();

INSERT INTO PAGAMENTO (VALOR_PAG, VENCIMENTO_PAG, ESTATUS_PAG, GRUPO_PAG, CLIENTE_PAG)
	VALUES ();