DROP DATABASE WEGET;
CREATE DATABASE WEGET;

USE WEGET;

CREATE TABLE FORNECEDOR(
COD_FOR INT NOT NULL AUTO_INCREMENT,
CNPJ_FOR VARCHAR(14) NOT NULL,
NOME_FOR VARCHAR(300) NOT NULL,
FANTASIA_FOR VARCHAR(250),
END_FOR VARCHAR(300) NOT NULL,
BAIRRO_FOR VARCHAR(100) NOT NULL,
ESTADO_FOR CHAR(2) NOT NULL,
TEL_FOR VARCHAR(10) NOT NULL,
EMAIL_FOR VARCHAR(300) NOT NULL,
CLASSIFICACAO_FOR INT NOT NULL,
CIDADE_FOR VARCHAR(68) NOT NULL,
CEP_FOR VARCHAR(10) NOT NULL,

PRIMARY KEY(COD_FOR)

)ENGINE=INNODB;

CREATE TABLE PRODUTO(
COD_PROD INT NOT NULL AUTO_INCREMENT,
DESCRICAO_PROD VARCHAR(500) NOT NULL,
QTDE_ESTOQUE_PROD DOUBLE NOT NULL,

PRIMARY KEY (COD_PROD)

)ENGINE=INNODB;

CREATE TABLE ANUNCIO(
COD_ANU INT NOT NULL AUTO_INCREMENT,
TEXTO_ANU VARCHAR(300) NOT NULL,
VALOR_ANU DOUBLE NOT NULL,
IMG_ANU VARCHAR(100) NOT NULL,
DATA_INICIO_ANU DATE NOT NULL,
DATA_FIM_ANU DATE NOT NULL,
QTDE_MIN_ANU INT NOT NULL,
QTDE_MAX_ANU INT NOT NULL,
ATIVO_ANU CHAR(1) NOT NULL,
FORNECEDOR_ANU INT NOT NULL,
PRODUTO_ANU INT NOT NULL,

PRIMARY KEY(COD_ANU),

CONSTRAINT FK_ANU_FOR FOREIGN KEY (FORNECEDOR_ANU) REFERENCES FORNECEDOR(COD_FOR),
CONSTRAINT FK_ANU_PRO FOREIGN KEY (PRODUTO_ANU) REFERENCES PRODUTO(COD_PROD)

)ENGINE=INNODB;

CREATE TABLE CLIENTE(
COD_CLI INT NOT NULL AUTO_INCREMENT,
CPF_CLI varchar(20) NOT NULL,
NOME_CLI VARCHAR(30) NOT NULL,
SOBRENOME_CLI VARCHAR(100) NOT NULL,
END_CLI VARCHAR(150) NOT NULL,
BAIRRO_CLI VARCHAR(100) NOT NULL,
COMPL_CLI varchar(30),
ESTADO_FOR CHAR(2) NOT NULL,
TEL_CLI VARCHAR(20) NOT NULL,
CEL_CLI VARCHAR(20) NOT NULL,
CIDADE_CLI VARCHAR(60) NOT NULL,
CEP_CLI CHAR(8) NOT NULL, 
DATA_NASC_CLI DATE NOT NULL,
EMAIL_CLI VARCHAR(150) NOT NULL,
SENHA VARCHAR(8) NOT NULL,

PRIMARY KEY (COD_CLI)

)ENGINE=INNODB;

CREATE TABLE GRUPO(
COD_GRU INT NOT NULL AUTO_INCREMENT,
QTDE_ATUAL_GRU INT NOT NULL,
ANUNCIO_GRU INT NOT NULL,

PRIMARY KEY(COD_GRU),

CONSTRAINT FK_ANUNCIO_GRUPO FOREIGN KEY (ANUNCIO_GRU) REFERENCES ANUNCIO(COD_ANU)

)ENGINE=INNODB;

CREATE TABLE PARTICIPA(
CLIENTE_PAR INT NOT NULL AUTO_INCREMENT,
GRUPO_PAR INT NOT NULL,
ATIVO_PAR CHAR(1) NOT NULL,

PRIMARY KEY(CLIENTE_PAR, GRUPO_PAR),

CONSTRAINT FK_CLIENTE_PARCIPA FOREIGN KEY (CLIENTE_PAR) REFERENCES CLIENTE(COD_CLI),
CONSTRAINT FK_GRUPO_PARCIPADO FOREIGN KEY (GRUPO_PAR) REFERENCES GRUPO(COD_GRU)

)ENGINE=INNODB;

CREATE TABLE PEDIDO(
COD_PED INT NOT NULL AUTO_INCREMENT,
QUANTIDADE_PED DOUBLE NOT NULL,
ANUNCIO_PED INT NOT NULL,
GRUPO_PED INT NOT NULL,

PRIMARY KEY(COD_PED),

CONSTRAINT FK_PEDIDO_GRUPO FOREIGN KEY (GRUPO_PED) REFERENCES GRUPO(COD_GRU),
CONSTRAINT FK_PEDIDO_ANUNCIO FOREIGN KEY (ANUNCIO_PED) REFERENCES ANUNCIO(COD_ANU)

)ENGINE=INNODB;

CREATE TABLE PAGAMENTO(
COD_PAG INT NOT NULL AUTO_INCREMENT,
VALOR_PAG DOUBLE NOT NULL,
VENCIMENTO_PAG DATE NOT NULL,
ESTATUS_PAG CHAR(1) NOT NULL,
GRUPO_PAG INT NOT NULL,
CLIENTE_PAG INT NOT NULL,

PRIMARY KEY(COD_PAG),

CONSTRAINT FK_PAG_POR_GRUPO FOREIGN KEY (GRUPO_PAG) REFERENCES GRUPO(COD_GRU),
CONSTRAINT FK_PAG_REF_CLI FOREIGN KEY (CLIENTE_PAG) REFERENCES CLIENTE(COD_CLI)

)ENGINE=INNODB;
